<?php
require_once('SvgIcon.php');
require_once('ArrowsHorizontalIcon.php');
require_once('BatteryIcon.php');
require_once('SearchIcon.php');
require_once('ArrowsVerticalIcon.php');
require_once('BarbellIcon.php');
require_once('QrCodeIcon.php');
require_once('CardsIcon.php');
require_once('HandsIcon.php');
require_once('FilterIcon.php');
require_once('ElementIcon.php');
require_once('calendarCheckIcon.php');